#42 For intel and intel-oneapi, set HAVE_GETTID macro as C5's environment contains its own gettid Linux system call available in the GNU standard library. The intel-classic environment does not have the gettid system function defined.
More details: https://github.com/NOAA-GFDL/FMS/issues/276

The error one sees is:
src/FMS/affinity/affinity.c:55:14: error: static declaration of 'gettid' follows non-static declaration
static pid_t gettid(void)
             ^
/usr/include/bits/unistd_ext.h:34:16: note: previous declaration is here
extern __pid_t gettid (void) __THROW;
               ^
1 error generated.